---
version: 2.1

# Command definitions
#commands:
    
# Job definitions
jobs:
  lint-code:
    docker:
      - image: python:3.7.3-stretch #ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Setup lint environment
          command: |
            make setup
      - run:
          name: Run lint checks
          command: |
            make lint
  
  build-docker-image:
    docker:
      - image: cimg/base:2022.10  
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          #docker_layer_caching: true # cost per run
      - run: |
          docker build -t circleci_id .
          docker image ls | grep circleci_id


# Workflow definitions
workflows:
  deploy:
    jobs:
      - lint-code
      - build-docker-image
      