apiVersion: v1
kind: Service
metadata:
  name: capstone-nginx-svc
  namespace: udacity-capstone
spec:
  selector:
    app: capstone-nginx-app
  ports:
    - name: http
      port: 8000
      targetPort: 80
  type: LoadBalancer